---
name: CGI-Application-Plugin-LogDispatch
version: 1.02
author:
  - 'Cees Hek <ceeshek@gmail.com>'
abstract: Plugin that adds Log::Dispatch support to CGI::Application
license: perl
requires:
  CGI::Application: 0
  Log::Dispatch: 0.21
  Scalar::Util: 0
  UNIVERSAL::require: 0
recommends:
  Class::ISA: 0
  Sub::WrapPackages: 0
provides:
  CGI::Application::Plugin::LogDispatch:
    file: lib/CGI/Application/Plugin/LogDispatch.pm
    version: 1.02
generated_by: Module::Build version 0.26
